name: ${project.artifactId}
main: ${project.groupId}.${project.artifactId}
description: ${project.name}
version: ${project.version}
author: xXSchrandXx
website: ${project.url}
database: false
softdepend: [AsyncWorldManager]
api-version: 1.13
commands:
  worldmanagergui:
    description: Hauptkommando von WorldSystemGUI.
    aliases: [wmgui]
    usage: /wmgui <> []